const KEY="fittrack-ai-v1";
let db=JSON.parse(localStorage.getItem(KEY)||'null')||{profile:{},weights:[],workouts:[],measurements:[],schedule:{}};
const days=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];
function save(){localStorage.setItem(KEY,JSON.stringify(db));render()}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function todayName(){return new Intl.DateTimeFormat("en-US",{weekday:"long"}).format(new Date())}
function showPage(id){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));document.getElementById(id).classList.add("active");document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("active",x.dataset.page===id));render()}
function toggleTheme(){document.body.classList.toggle("dark");localStorage.setItem("ft-dark",document.body.classList.contains("dark"))}
if(localStorage.getItem("ft-dark")==="true")document.body.classList.add("dark");
function openModal(html){document.getElementById("modalContent").innerHTML=html;document.getElementById("modal").classList.add("show")}
function closeModal(){document.getElementById("modal").classList.remove("show")}
function openWeightModal(){openModal(`<h2>Update weight</h2><form onsubmit="addWeight(event)"><label>Date<input id="wDate" type="date" value="${new Date().toISOString().slice(0,10)}"></label><label>Weight (kg)<input id="wValue" type="number" step="0.1" required placeholder="70"></label><button class="primary">Save weight</button></form>`)}
function addWeight(e){e.preventDefault();db.weights.push({date:wDate.value,weight:+wValue.value});db.weights.sort((a,b)=>a.date.localeCompare(b.date));closeModal();save()}
function openWorkoutModal(){openModal(`<h2>Log workout</h2><form onsubmit="addWorkout(event)"><label>Date<input id="xDate" type="date" value="${new Date().toISOString().slice(0,10)}"></label><label>Workout / exercise<input id="xName" required placeholder="Running, push-ups..."></label><label>Duration (min)<input id="xDuration" type="number" min="0" value="0"></label><label>Distance (km)<input id="xDistance" type="number" step="0.01" min="0" value="0"></label><label>Sets / reps / result<input id="xResult" placeholder="3 × 15"></label><label>Difficulty (1–10)<input id="xDiff" type="number" min="1" max="10"></label><label>Notes<textarea id="xNotes" rows="3" style="width:100%;padding:10px;border:1px solid #d1d5db;border-radius:10px"></textarea></label><button class="primary">Save workout</button></form>`)}
function addWorkout(e){e.preventDefault();db.workouts.push({date:xDate.value,name:xName.value,duration:+xDuration.value||0,distance:+xDistance.value||0,result:xResult.value,diff:xDiff.value,notes:xNotes.value});closeModal();save()}
function openMeasurementModal(){openModal(`<h2>Add measurement</h2><form onsubmit="addMeasurement(event)"><label>Date<input id="mDate" type="date" value="${new Date().toISOString().slice(0,10)}"></label><label>Waist (cm)<input id="mWaist" type="number" step="0.1"></label><label>Chest (cm)<input id="mChest" type="number" step="0.1"></label><label>Arm (cm)<input id="mArm" type="number" step="0.1"></label><label>Leg (cm)<input id="mLeg" type="number" step="0.1"></label><button class="primary">Save measurement</button></form>`)}
function addMeasurement(e){e.preventDefault();db.measurements.push({date:mDate.value,waist:+mWaist.value||null,chest:+mChest.value||null,arm:+mArm.value||null,leg:+mLeg.value||null});closeModal();save()}
function saveProfile(){db.profile={name:pName.value,age:+pAge.value||null,height:+pHeight.value||null,start:+pStart.value||null,target:+pTarget.value||null,goal:pGoal.value};save();alert("Profile saved")}
function addScheduleDay(){openModal(`<h2>Add workout day</h2><form onsubmit="saveSchedule(event)"><label>Day<select id="sDay">${days.map(d=>`<option>${d}</option>`).join("")}</select></label><label>Exercises (one per line)<textarea id="sExercises" rows="7" placeholder="Running — 2.5 km&#10;Push-ups — 3 × 15&#10;Squats — 3 × 20" style="width:100%;padding:10px;border:1px solid #d1d5db;border-radius:10px"></textarea></label><button class="primary">Save day</button></form>`)}
function saveSchedule(e){e.preventDefault();db.schedule[sDay.value]=sExercises.value.split("\n").map(x=>x.trim()).filter(Boolean);closeModal();save()}
function deleteSchedule(day){delete db.schedule[day];save()}
function render(){renderHome();renderWorkout();renderProgress();renderAnalytics();renderProfile()}
function renderHome(){const p=db.profile,w=db.weights,latest=w.at(-1);currentWeight.textContent=latest?latest.weight+" kg":"—";let delta=w.length>1?(latest.weight-w[0].weight):0;weightDelta.textContent=w.length>1?`${delta>0?"+":""}${delta.toFixed(1)} kg since first entry`:"Add weight entries";totalWorkouts.textContent=db.workouts.length;streak.textContent=calcStreak();let prog=0;if(p.start&&p.target&&latest){prog=Math.max(0,Math.min(100,Math.abs((latest.weight-p.start)/(p.target-p.start))*100))}goalProgress.textContent=Math.round(prog)+"%";let day=todayName(),ex=db.schedule[day]||[];todayTitle.textContent=ex.length?`${day} workout`:"Rest / no plan";todaySummary.textContent=ex.length?`${ex.length} planned exercise${ex.length>1?"s":""}`:"Add exercises in Profile";recent.innerHTML=db.workouts.slice(-5).reverse().map(x=>`<div class="activity"><div><b>${esc(x.name)}</b><div class="muted">${x.date}</div></div><span>${x.duration||0} min</span></div>`).join("")||'<p class="muted">No workouts logged yet.</p>'}
function calcStreak(){let dates=[...new Set(db.workouts.map(x=>x.date))].sort().reverse();if(!dates.length)return 0;let s=0,d=new Date();for(let i=0;i<dates.length;i++){let want=new Date(d);want.setDate(d.getDate()-i);if(dates[i]===want.toISOString().slice(0,10))s++;else break}return s}
function renderWorkout(){schedule.innerHTML=days.map(d=>`<div class="scheduleRow"><div><b>${d}</b><div class="muted">${(db.schedule[d]||[]).length} exercises</div></div><button class="pill" onclick="addDayFromRow('${d}')">Edit</button></div>`).join("");let ex=db.schedule[todayName()]||[];todayExercises.innerHTML=ex.map((x,i)=>`<div class="exercise"><span>${esc(x)}</span><span class="pill">${i+1}</span></div>`).join("")||'<p class="muted">Nothing planned for today.</p>'}
function addDayFromRow(day){openModal(`<h2>${day}</h2><form onsubmit="updateDay(event,'${day}')"><label>Exercises<textarea id="uExercises" rows="8" style="width:100%;padding:10px;border:1px solid #d1d5db;border-radius:10px">${esc((db.schedule[day]||[]).join("\n"))}</textarea></label><button class="primary">Save</button></form><button class="secondary" onclick="deleteSchedule('${day}')">Delete day</button>`)}
function updateDay(e,day){e.preventDefault();db.schedule[day]=uExercises.value.split("\n").map(x=>x.trim()).filter(Boolean);closeModal();save()}
function renderProgress(){let c=document.getElementById("weightChart"),ctx=c.getContext("2d"),W=c.width,H=c.height;ctx.clearRect(0,0,W,H);let a=db.weights;if(a.length){let vals=a.map(x=>x.weight),min=Math.min(...vals)-1,max=Math.max(...vals)+1;ctx.beginPath();a.forEach((x,i)=>{let xx=45+(W-70)*(i/Math.max(1,a.length-1)),yy=H-35-(H-65)*((x.weight-min)/(max-min));i?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy)});ctx.strokeStyle=getComputedStyle(document.body).color;ctx.lineWidth=3;ctx.stroke();a.forEach((x,i)=>{let xx=45+(W-70)*(i/Math.max(1,a.length-1)),yy=H-35-(H-65)*((x.weight-min)/(max-min));ctx.beginPath();ctx.arc(xx,yy,4,0,7);ctx.fillStyle=getComputedStyle(document.body).color;ctx.fill()})}else{ctx.fillText("Add at least one weight entry to see your chart.",25,60)}weightHistory.innerHTML=a.slice(-8).reverse().map(x=>`<div class="activity"><span>${x.date}</span><b>${x.weight} kg</b></div>`).join("")||'<p class="muted">No weight history.</p>';measurements.innerHTML=db.measurements.slice(-5).reverse().map(x=>`<div class="activity"><span>${x.date}</span><span>Waist ${x.waist??"—"} · Chest ${x.chest??"—"} · Arm ${x.arm??"—"} · Leg ${x.leg??"—"}</span></div>`).join("")||'<p class="muted">No measurements yet.</p>';let runs=db.workouts.filter(x=>x.distance>0);records.innerHTML=`<div class="record"><span>Longest logged distance</span><b>${Math.max(0,...runs.map(x=>x.distance)).toFixed(2)} km</b></div><div class="record"><span>Longest workout</span><b>${Math.max(0,...db.workouts.map(x=>x.duration))} min</b></div>`}
function renderAnalytics(){let n=db.workouts.length,completion.textContent=n?Math.round(db.workouts.filter(x=>x.name).length/n*100)+"%":"0%";distance.textContent=db.workouts.reduce((s,x)=>s+(x.distance||0),0).toFixed(2)+" km";duration.textContent=db.workouts.reduce((s,x)=>s+(x.duration||0),0)+" min";let p=db.profile,w=db.weights,lines=[];if(n)lines.push(`You logged <b>${n}</b> workout${n>1?"s":""}.`);if(w.length>1){let d=w.at(-1).weight-w[0].weight;lines.push(`Your recorded weight changed <b>${d>=0?"+":""}${d.toFixed(1)} kg</b> from ${w[0].date} to ${w.at(-1).date}.`)}if(p.target&&w.length){let gap=p.target-w.at(-1).weight;lines.push(`You are <b>${Math.abs(gap).toFixed(1)} kg</b> ${gap>0?"below":"above"} your target weight.`)}if(!lines.length)lines.push("Log workouts and weight entries to generate a data-based review.");review.innerHTML=lines.map(x=>`<p>${x}</p>`).join("")}
function renderProfile(){let p=db.profile;pName.value=p.name||"";pAge.value=p.age||"";pHeight.value=p.height||"";pStart.value=p.start||"";pTarget.value=p.target||"";pGoal.value=p.goal||"Muscle Gain";planEditor.innerHTML=days.map(d=>`<div class="scheduleRow"><div><b>${d}</b><div class="muted">${(db.schedule[d]||[]).join(" · ")||"No workout planned"}</div></div><button class="pill" onclick="addDayFromRow('${d}')">Edit</button></div>`).join("")}
function exportData(){let blob=new Blob([JSON.stringify(db,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="fittrack-ai-data.json";a.click();URL.revokeObjectURL(a.href)}
function resetData(){if(confirm("Delete all FitTrack AI data?")){localStorage.removeItem(KEY);location.reload()}}
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js"));
render();